# Generated by Django 4.2.1 on 2023-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('comfir_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Login',
            new_name='Signin',
        ),
    ]
