# Generated by Django 4.2.1 on 2023-05-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_signup_rename_login_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signin',
            new_name='Login',
        ),
    ]
