# Generated by Django 4.2.1 on 2023-05-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='signup',
        ),
    ]
