# Generated by Django 4.2.1 on 2023-05-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
