# Generated by Django 4.2.1 on 2023-05-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
