# Generated by Django 4.2.1 on 2023-05-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
